Allow at most one default in a member list
l20n/spec pull request #10
Opened 2016-10-09 00:13 UTC by spagy

2016-10-13 13:11 UTC, stasm commented
Thanks for the PR @spagy!  I agree that this is desirable but I'd also like to hear what @Pike and @zbraniecki think about this.

2016-10-13 13:14 UTC, stasm requested changes

2016-10-13 13:14 UTC, stasm commented on grammar.ebnf
> +nondefault-member    ::= member-base
I think this can be expressed by:

    member         ::= '[' keyword ']' __ pattern NL;
    default-member ::= '*' member

2016-10-13 13:14 UTC, stasm commented on grammar.ebnf
> +member-list          ::= NL (__ nondefault-member)* (__ default-member) (__ nondefault-member)*
We'll need to split `member-list` into `traits-list` and `variants-list`, which are both lists of `members`.  Only the `variant-list` should require one `default-member`.

2016-10-13 13:34 UTC, Pike commented on grammar.ebnf
> -message              ::= identifier __ '=' __ (pattern | pattern member-list | member-list);
We still need to keep message, too.

2016-10-13 13:35 UTC, Pike commented
stas and I also talked about requiring the default member for variants.

This might be the PR to add that to, if we think we should do that.

2016-10-13 20:32 UTC, spagy commented on grammar.ebnf
> +nondefault-member    ::= member-base
Agreed, that's a nicer solution.

2016-10-13 20:32 UTC, spagy commented on grammar.ebnf
> -message              ::= identifier __ '=' __ (pattern | pattern member-list | member-list);
Completely right, I'm not quite sure why that disappeared

2016-10-13 20:39 UTC, spagy commented on grammar.ebnf
> +member-list          ::= NL (__ nondefault-member)* (__ default-member) (__ nondefault-member)*
Done

2016-10-13 20:42 UTC, spagy commented
I've added ```default-list```, which is used to simplify the definitions of ```trait-list``` and ```variant-list``` but I don't really like the name. To me it sounds like ```default-list``` is the definition of a "default list" rather than a list involving a default member. If anyone has a suggestion for a better name I'd be happy to change it.

2016-10-13 20:43 UTC, spagy commented
@Pike, it looks like that's what @stasm was talking about in his previous comment. If that is what you're talking about then I've added that. Otherwise, would you be able to explain further?

2016-10-13 20:47 UTC, spagy commented
This commit log is getting slightly messy. Once everything is sorted out I'd be happy to rebase.

2016-11-08 10:43 UTC, stasm commented
@zbraniecki How hard would it be to enforce this in the current parsers implementations?

2016-12-01 15:57 UTC, GlenDC commented
Are the EBNF grammar changes in this PR already approved?

2017-01-20 15:25 UTC, stasm commented
We moved the development of the core of l20n into a new project and a new repository.  I re-file this issue there and submitted a PR based on this one: https://github.com/projectfluent/syntax/pull/13

2017-01-20 15:31 UTC, closed without merging